apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: v
    tier: backend
    deployedBy: deploy-node-app
  name: v
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: v
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: v
        tier: backend
        deployedBy: deploy-node-app
    spec:
      containers:
        - image: jefftian/vvv:latest
          imagePullPolicy: Always
          name: v
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi
          envFrom: []
      restartPolicy: Always
      terminationGracePeriodSeconds: 30