apiVersion: v1
kind: Service
metadata:
  name: v
  annotations:
    dev.okteto.com/auto-ingress: 'true'
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: v
    tier: backend
