# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - run: curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      - run: chmod +x ./kubectl
      - run: sudo mv ./kubectl /usr/local/bin/kubectl
      - run: mkdir ${HOME}/.kube
      - run: npm i -g k8ss
      - run: echo -e "machine github.com\n  login ${{secrets.GH_TOKEN}}" > ~/.netrc
      - run: git clone https://github.com/Jeff-Tian/k8s-config.git ${HOME}/k8s-config
      - run: npm run okteto

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 12
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
          cache: 'npm'
      - run: npm i
      - run: cd client && npm i
      - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
      - run: npm run build
      - run: docker build -t jefftian/vvv .
      - run: docker images
      - run: docker run --rm --network host -e CI=true -d -p 127.0.0.1:3000:3000 --name vvv jefftian/vvv
      - run: docker ps | grep -q v
      - run: docker ps -aqf "name=vvv$"
      - run: docker push jefftian/vvv
      - run: docker logs $(docker ps -aqf name=vvv$)
      - run: curl localhost:3000 || docker logs $(docker ps -aqf name=vvv$)
      - run: docker kill vvv || echo "vvv killed"
      - run: docker rm vvv || echo "vvv removed"

  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci && cd client && npm i
      - run: npm run build --if-present
      - run: npm run server-test
      - run: npm run client-test
#      - run: npm run test:e2e
#      - run: npm run test:cov