# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  update-napptive:
    name: update napptive
    if: ${{ always() }}
    needs: deploy-napptive
    runs-on: ubuntu-latest
    env:
      PLAYGROUND_PAT: ${{ secrets.PLAYGROUND_PAT }}
      MY_OPENSSL_PASSWORD: ${{ secrets.MY_OPENSSL_PASSWORD }}
    steps:
      - run: echo "${PLAYGROUND_PAT}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter 5 -k "${MY_OPENSSL_PASSWORD}"
      - uses: actions/checkout@v2
      - run: echo "Downloading NAPPTIVE Playground CLI"
      - run: curl -O https://storage.googleapis.com/artifacts.playground.napptive.dev/installer.sh && bash installer.sh

      - run: echo "Downloading Kubectl"
      - run: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - run: chmod +x kubectl
      - run: echo "Login into NAPPTIVE Playground"
      - run: playground login --pat
      - run: playground get-kubeconfig
      - run: ls ~/.napptive/default/napptive-kubeconfig

      - name: update
        env:
          PLAYGROUND_PAT: ${{ secrets.PLAYGROUND_PAT }}
        run: |
          export PATH=$PATH:$(pwd)
          echo "Forcing rolling update to download newest image"
          export IMAGE="jefftian/vvv:latest"
          echo "Update image... ${IMAGE}"
          export PATCH='{"spec":{"workload":{"spec":{"containers":\ [{"name":"v", "image":"${IMAGE}"}]}}}}'
          echo "patch = ${PATCH}"
          kubectl --kubeconfig ~/.napptive/default/napptive-kubeconfig patch deploy v --patch 
          '{"spec":{"template":{"spec":{"containers":[{"image":"jefftian/vvv","name":"v"}]}}}}' --type=merge

  deploy-napptive:
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true
    env:
      PLAYGROUND_PAT: ${{ secrets.PLAYGROUND_PAT }}
    steps:
      - run: echo "${PLAYGROUND_PAT}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter 5 -k "${MY_OPENSSL_PASSWORD}"
      - uses: actions/checkout@v2
      - run: echo "Downloading NAPPTIVE Playground CLI"
      - run: curl -O https://storage.googleapis.com/artifacts.playground.napptive.dev/installer.sh && bash installer.sh

      - run: echo "Downloading Kubectl"
      - run: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - run: chmod +x kubectl
      - run: echo "Login into NAPPTIVE Playground"
      - run: playground login --pat
      - run: playground get-kubeconfig
      - run: ls ~/.napptive/default/napptive-kubeconfig

      - name: update
        env:
          PLAYGROUND_PAT: ${{ secrets.PLAYGROUND_PAT }}
        run: |
          export PATH=$PATH:$(pwd)
          echo "Forcing rolling update to download newest image"
          export IMAGE="jefftian/vvv:latest"
          echo "Update image... ${IMAGE}"
          kubectl --kubeconfig ~/.napptive/default/napptive-kubeconfig patch deploy uni-orders --patch '{"spec":{"template":{"spec":{"containers":[{"image":"${IMAGE}","name":"v"}]}}}}' --type=merge

  deploy-okteto:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - run: curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      - run: chmod +x ./kubectl
      - run: sudo mv ./kubectl /usr/local/bin/kubectl
      - run: mkdir ${HOME}/.kube
      - run: npm i -g k8ss
      - run: echo -e "machine github.com\n  login ${{secrets.GH_TOKEN}}" > ~/.netrc
      - run: git clone https://github.com/Jeff-Tian/k8s-config.git ${HOME}/k8s-config
      - run: npm run okteto

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.10.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.10.0
          cache: 'npm'
      - run: npm i
      - run: cd client && npm i
      - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
      - run: npm run build
      - run: docker build -t jefftian/vvv .
      - run: docker images
      - run: docker run --rm --network host -e CI=true -d -p 127.0.0.1:3000:3000 --name vvv jefftian/vvv
      - run: docker ps | grep -q v
      - run: docker ps -aqf "name=vvv$"
      - run: docker push jefftian/vvv
      - run: docker logs $(docker ps -aqf name=vvv$)
      - run: curl localhost:3000 || docker logs $(docker ps -aqf name=vvv$)
      - run: docker kill vvv || echo "vvv killed"
      - run: docker rm vvv || echo "vvv removed"

  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.10.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci && cd client && npm i
      - run: npm run build --if-present
      - run: npm run server-test
      - run: npm run client-test-exit
#      - run: npm run test:e2e
#      - run: npm run test:cov